blank_issues_enabled: true
contact_links:
  - name: 👥 Discussions
    url:  https://github.com/Microsoft-Bootcamp/overview3005202/discussions/new
    about: Please use discussions for issues that are not a bug, enhancement or feature request
